app_backend:
    resource: "@AppBackendBundle/Resources/config/routing.yml"
    prefix:   /

app_front_end:
    resource: "@AppFrontEndBundle/Resources/config/routing.yml"
    prefix:   /

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

