<?php

namespace App\BackendBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * @author Rezgui Mohamed <rezgui_isetch@hotmail.fr>
 * 
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{
}
